checks:
  javascript: true

filter:
  paths:
    - "src/"
  excluded_paths:
    - "test/"

build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          -
            command: eslint-run
            use_website_config: false
      environment:
        node:
          version: 8.11.1
    tests: true

# Not needed: we use the CodeClimate coverage badge anyway.
#tools:
#  external_code_coverage:
#    # In seconds
#    timeout: 600
