language: node_js

env:
  global:
    - CC_TEST_REPORTER_ID=c33e0157337760958191e73532ea32aca9e54dee6edd7a941e84f0e33bbe3165

matrix:
  allow_failures:
    - node_js: 10

node_js:
  - 8
  - 10

before_script:
  # Codecov preparation.
  - npm install -g codecov

  # CodeClimate preparation.
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter -d before-build

script:
  yarn test-ci

after_script:
  # CodeCode report.
  - codecov

  # CodeClimate report.
  - ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT
